### ISSUE TITLE
Hyperion.SerializerOptions exception

### ISSUE THREAD

**Issue by jmnowick** [Horusiath/Akkling#118]
Trying to run the most basic example and I get an exception as follows.

"The type initializer for 'Hyperion.SerializerOptions' threw an exception."

running
Akka 1.3.13
Akkling 0.93
which has Akka.Serialization.Hyperion 1.3.8-beta66
hyperion 0.98

**Comment by Horusiath** [comment]
1. Is that the entire exception message?
2. Are you sure that all packages and assemblies are in place? I remember that using nuget for resolving packages didn't load all dependecies (I think that Hyperion package itself was missing), however it works fine with Paket.

**Comment by chnlkw** [comment]
i met the same exception when i use akkling to creating the actor system. I have the same package version as @jmnowick . I use Visual Studio 2019 with dotnet core 3.0-preview-6

```
use system = Akka.FSharp.System.create "system-create" (Akka.FSharp.Configuration.load()) // 1. success
use system = Akka.FSharp.System.create "system-create" ( Configuration.defaultConfig() ) // 2. fail
use system = System.create "my-system" <| Configuration.defaultConfig() // 3. fail 
```

The exception of 2 and 3 are same below:
```
Result StackTrace:	
at Hyperion.SerializerOptions..ctor(Boolean versionTolerance, Boolean preserveObjectReferences, IEnumerable`1 surrogates, IEnumerable`1 serializerFactories, IEnumerable`1 knownTypes, Boolean ignoreISerializable)
   at Akka.Serialization.HyperionSerializer..ctor(ExtendedActorSystem system, HyperionSerializerSettings settings)
   at Akka.Serialization.HyperionSerializer..ctor(ExtendedActorSystem system)
----- Inner Stack Trace -----
   at Hyperion.SerializerFactories.ExceptionSerializerFactory..ctor()
   at Hyperion.SerializerOptions..cctor()
----- Inner Stack Trace -----
   at System.Reflection.TypeExtensions.GetMethod(Type type, String name, BindingFlags bindingAttr)
   at Hyperion.SerializerFactories.ExceptionSerializerFactory..cctor()
Result Message:	
System.TypeInitializationException : The type initializer for 'Hyperion.SerializerOptions' threw an exception.
---- System.TypeInitializationException : The type initializer for 'Hyperion.SerializerFactories.ExceptionSerializerFactory' threw an exception.
-------- System.ArgumentNullException : Value cannot be null.
Parameter name: type
```

**Comment by jmnowick** [comment]
Update. 
If I target SDK to 2.2 everything works fine.
