### ISSUE TITLE
Streams example is broken 

### ISSUE THREAD

**Issue by anpin** [Horusiath/Akkling#163]
Hi, thank you for your effort with this project! I found that `streams.fsx` example is throwing following exception when I do 
`dotnet fsi ./streams.fsx`
```
System.InvalidCastException: Unable to cast object of type 'Akka.NotUsed' to type 'Microsoft.FSharp.Core.Unit'.
   at Akka.Streams.Implementation.Module.<>c__DisplayClass28_0`3.<Compose>b__0(Object x, Object y)
   at Akka.Streams.Implementation.MaterializerSession.ResolveMaterialized(IMaterializedValueNode node, IDictionary`2 values, Int32 spaces)
   at Akka.Streams.Implementation.MaterializerSession.ResolveMaterialized(IMaterializedValueNode node, IDictionary`2 values, Int32 spaces)
   at Akka.Streams.Implementation.MaterializerSession.ResolveMaterialized(IMaterializedValueNode node, IDictionary`2 values, Int32 spaces)
   at Akka.Streams.Implementation.MaterializerSession.MaterializeModule(IModule module, Attributes effectiveAttributes)
   at Akka.Streams.Implementation.MaterializerSession.Materialize()
   at Akka.Streams.Implementation.ActorMaterializerImpl.Materialize[TMat](IGraph`2 runnable, Func`2 subFlowFuser, Attributes initialAttributes)
   at Akka.Streams.Implementation.ActorMaterializerImpl.Materialize[TMat](IGraph`2 runnable)
   at Akka.Streams.Dsl.RunnableGraph`1.Run(IMaterializer materializer)
   at FSI_0002.it@105.Invoke(Unit unitVar) in /home/a/Akkling/examples/streams.fsx:line 105
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 517
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
--- End of stack trace from previous location ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 454
   at Microsoft.FSharp.Control.AsyncPrimitives.QueueAsyncAndWaitForResultSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1140
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1511
   at <StartupCode$FSI_0002>.$FSI_0002.main@() in /home/a/Akkling/examples/streams.fsx:line 104
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by ingted** [comment]
For me, streams.fsx works fine...

```
Welcome to F# Interactive for .NET Core in Visual Studio. To execute code, either
  1. Use 'Send to Interactive' (Alt-Enter or right-click) from an F# script. The F# Interactive process will
     use any global.json settings associated with that script.
  2. Press 'Enter' to start. The F# Interactive process will use default settings.
> 

Microsoft (R) F# Interactive version 12.4.0.0 for F# 7.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> val it: unit = ()

>[Loading G:\coldfar_py\sharftrade7\Experiments\Persistence.Query\PQ001\fsx\general.ref.fsx]
module FSI_0003.General.ref



Program.fs(6,11): error FS0039: The namespace 'Streams' is not defined.

> 
[Loading G:\coldfar_py\sharftrade7\Experiments\Persistence.Query\PQ001\fsx\general.ref.fsx]
module FSI_0005.General.ref

> 
Binding session to 'G:\coldfar_py\sharftrade7\Experiments\Persistence.Query\PQ001\fsx\..\bin\net7.0\Akka.dll'...
Binding session to 'G:\coldfar_py\sharftrade7\Experiments\Persistence.Query\PQ001\fsx\..\bin\net7.0\Akka.Streams.dll'...
Binding session to 'G:\coldfar_py\sharftrade7\Experiments\Persistence.Query\PQ001\fsx\..\bin\net7.0\Akkling.dll'...
Binding session to 'G:\coldfar_py\sharftrade7\Experiments\Persistence.Query\PQ001\fsx\..\bin\net7.0\Akkling.Streams.dll'...
LOREM
IPSUM
IS
SIMPLY
DUMMY
TEXT
OF
THE
PRINTING
AND
TYPESETTING
INDUSTRY.
LOREM
IPSUM
HAS
BEEN
THE
INDUSTRY'S
STANDARD
DUMMY
TEXT
EVER
SINCE
THE
1500S,
WHEN
AN
UNKNOWN
PRINTER
TOOK
A
GALLEY
OF
TYPE
AND
SCRAMBLED
IT
TO
MAKE
A
TYPE
SPECIMEN
BOOK.
val system: Akka.Actor.ActorSystem = akka://streams-sys
val mat: ActorMaterializer
       Lorem Ipsum is simply dummy text of the printing and "+[213 chars]
val it: unit = ()

> 
val behavior: targetRef: ICanTell<'a> -> m: Actor<'a> -> Effect<'a>
val spawnActor: targetRef: ICanTell<'a> -> IActorRef<'a>

> 
val s: IActorRef<string> = [akka://streams-sys/user/$a#1109106238]
val it: unit = ()

>Received: Boo

world
hello
val sink: Sink<string,Async<unit>> =
  Sink(SinkShape`1([Select.in] []), 
  CompositeModule [15876907%08x]
  Name: foreachSink
  Modules:
    foreachSink
  Downstreams: 
    Select.out -> Ignore.in
  Upstreams: 
    Ignore.in -> Select.out
  MatValue: Transform(Atomic(foreachSink[32701678])))
val consumer: Sink<string,unit> =
  Sink(SinkShape`1([MergeHub.in] []), 
  CompositeModule [5020285%08x]
  Name: 
  Modules:
    GraphStage(Akka.Streams.Dsl.MergeHub`1+HubSink[System.String]) [33607346%08x]
  Downstreams: 
  Upstreams: 
  MatValue: Transform(Atomic([33607346])))
val it: unit = ()

> 
```

**Comment by ingted** [comment]
Have only reference in general.ref.fsx

```
#if INTERACTIVE

#I @"..\bin\net7.0"
#r @"Akka.dll"
#r @"Akka.DistributedData.dll"
#r @"Akka.Persistence.dll"
#r @"Akka.Streams.dll"
#r @"Akkling.dll"
#r @"Akkling.Cluster.Sharding.dll"
#r @"Akkling.Persistence.dll"
#r @"Akkling.DistributedData.dll"
#r @"Akkling.Streams.dll"
#r @"NodaTime.dll"
#r @"Argu.dll"
#r @"Nodatime.dll"
#r @"NLog.dll"

#endif
```

**Comment by ingted** [comment]
PS. I am using a build from commit 62080681cd6e79a51100b38b4c49d0b24634f30e

**Comment by ingted** [comment]
The workaround is:

```
module Source =
    let singleton s = 
        Source.Single(s).MapMaterializedValue(Func<Akka.NotUsed,Akka.NotUsed>(fun _ -> Akka.NotUsed.Instance))    
        
```

**Comment by ingted** [comment]
Process A:

![image](https://user-images.githubusercontent.com/4289161/210188856-c25aebae-6bb6-425f-af83-7a2b4ff19b5d.png)

Process B:
![image](https://user-images.githubusercontent.com/4289161/210188863-23efc36f-c544-4e6d-8b4e-cd6bc988e5cd.png)

**Comment by ingted** [comment]
my fork:
https://github.com/ingted/Akkling
