### ISSUE TITLE
SerializationException: Serializer not found for type Object

### ISSUE THREAD

**Issue by vasily-kirichenko** [Horusiath/Akkling#53]
```fsharp
#r @"../packages/Akka/lib/net45/Akka.dll"
#r @"../packages/Hyperion/lib/net45/Hyperion.dll"
#r @"../packages/Newtonsoft.Json/lib/net45/Newtonsoft.Json.dll"
#r @"../packages/Akkling/lib/net45/Akkling.dll"
#r @"../packages/Akka.Streams/lib/net45/Akka.Streams.dll"
#r @"../packages/Akkling/lib/net45/Akkling.dll"
#r @"../packages/Reactive.Streams/lib/net45/Reactive.Streams.dll"
#r @"../packages/Akkling.Streams/lib/net45/Akkling.Streams.dll"

open Akka.Streams
open Akka.Streams.Dsl
open Akka 
open System.Numerics
open Akka.IO
open System.IO
open System
open Akkling
open Akkling.Streams

let system = System.create "system" (Configuration.defaultConfig())
```
```
--> Referenced 'E:\github\AkkaNetTest1\AkkaNetTest1\../packages/Akka/lib/net45/Akka.dll'


--> Referenced 'E:\github\AkkaNetTest1\AkkaNetTest1\../packages/Hyperion/lib/net45/Hyperion.dll'


--> Referenced 'E:\github\AkkaNetTest1\AkkaNetTest1\../packages/Newtonsoft.Json/lib/net45/Newtonsoft.Json.dll'


--> Referenced 'E:\github\AkkaNetTest1\AkkaNetTest1\../packages/Akkling/lib/net45/Akkling.dll'


--> Referenced 'E:\github\AkkaNetTest1\AkkaNetTest1\../packages/Akka.Streams/lib/net45/Akka.Streams.dll'


--> Referenced 'E:\github\AkkaNetTest1\AkkaNetTest1\../packages/Akkling/lib/net45/Akkling.dll'


--> Referenced 'E:\github\AkkaNetTest1\AkkaNetTest1\../packages/Reactive.Streams/lib/net45/Reactive.Streams.dll'


--> Referenced 'E:\github\AkkaNetTest1\AkkaNetTest1\../packages/Akkling.Streams/lib/net45/Akkling.Streams.dll'

> 
Binding session to 'E:\github\AkkaNetTest1\AkkaNetTest1\../packages/Akka/lib/net45/Akka.dll'...
[WARNING][24-Apr-17 17:54:13][Thread 0001][ActorSystem(system)] The type name for serializer 'hyperion' did not resolve to an actual Type: 'Akka.Serialization.HyperionSerializer, Akka.Serialization.Hyperion'
Binding session to 'E:\github\AkkaNetTest1\AkkaNetTest1\../packages/Newtonsoft.Json/lib/net45/Newtonsoft.Json.dll'...
[WARNING][24-Apr-17 17:54:13][Thread 0001][ActorSystem(system)] Serialization binding to non existing serializer: 'hyperion'
System.Runtime.Serialization.SerializationException: Serializer not found for type Object
   at Akka.Serialization.Serialization.FindSerializerForType(Type objectType)
   at Akka.Actor.Internal.ActorSystemImpl.WarnIfJsonIsDefaultSerializer()
   at Akka.Actor.Internal.ActorSystemImpl.Start()
   at Akkling.System.create(String name, Config config)
   at <StartupCode$FSI_0003>.$FSI_0003.main@() in E:\github\AkkaNetTest1\AkkaNetTest1\Script1.fsx:line 21
Stopped due to error
> 
```

**Comment by Horusiath** [comment]
Unfortunately this is a problem with the fact that Akka.Serialization.Hyperion still has prerelease flag on it. You need to download it manually using `-pre` flag on NuGet (or `prerelease` on Paket). 

This is due to the fact, that default Akka.NET serializer hit weird edge cases in F# discriminated unions, while FsPickler was unable to server context-dependent surrogates required by Akka.NET itself.

**Comment by vasily-kirichenko** [comment]
Thanks, it works.
