### ISSUE TITLE
Trying to modify an example to use Cassandra throws exception about missing ReplayMessagesAsync

### ISSUE THREAD

**Issue by MClode** [Horusiath/Akkling#95]
I am attempting to modify one of the examples to use Akka.Persistence.Cassandra, but it is failing with this Exception:

```[ERROR][20/02/2018 17:59:28][Thread 0014][akka://example/user/counter-1] Method 'ReplayMessagesAsync' in type 'Akka.Persistence.Cassandra.Journal.CassandraJournal' from assembly 'Akka.Persistence.Cassandra, Version=1.0.6.3, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Cause: [akka://example/user/counter-1#1564671488]: Akka.Actor.ActorInitializationException: Exception during creation ---> System.TypeLoadException: Method 'ReplayMessagesAsync' in type 'Akka.Persistence.Cassandra.Journal.CassandraJournal' from assembly 'Akka.Persistence.Cassandra, Version=1.0.6.3, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at Akka.Persistence.PersistenceExtension.CreatePlugin(ExtendedActorSystem system, String configPath, Config pluginConfig)
   at Akka.Persistence.PersistenceExtension.NewPluginHolder(ExtendedActorSystem system, String configPath, String fallbackPath)
   at Akka.Persistence.PersistenceExtension.<>c__DisplayClass25_0.<PluginHolderFor>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Akka.Persistence.PersistenceExtension.JournalFor(String journalPluginId)
   at Akka.Persistence.Eventsourced.get_Journal()
   at Akka.Persistence.Eventsourced.AroundPreStart()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.Create(Exception failure)
   --- End of inner exception stack trace ---
   at Akka.Actor.ActorCell.Create(Exception failure)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)
```

My versions:
```
nuget Akka 1.3.4 restriction: >= net452
nuget Akka.Persistence 1.3.4 restriction: >= net452
nuget Akka.Serialization.Hyperion 1.3.4-beta58 restriction: >= net452
nuget Akka.Streams 1.3.4 restriction: >= net452
nuget Akkling 0.7 restriction: >= net452
nuget Akkling.Persistence 0.7 restriction: >= net452
nuget Akkling.Streams 0.7 restriction: >= net452
nuget Akka.Persistence.Cassandra 1.0.6.3-beta restriction: >= net452
```

Here is my code as a script:

```
#r "../packages/Akka/lib/net45/Akka.dll"
#r "../packages/Akkling/lib/net45/Akkling.dll"
#r "../packages/Hyperion/lib/net45/Hyperion.dll"
#r "../packages/Akka.Serialization.Hyperion/lib/net45/Akka.Serialization.Hyperion.dll"
#r "../packages/FsPickler/lib/net45/FsPickler.dll"
#r "../packages/Newtonsoft.Json/lib/net45/Newtonsoft.Json.dll"
#r "../packages/Akkling/lib/net45/Akkling.dll"
#r "../packages/Akka.Persistence/lib/net45/Akka.Persistence.dll"
#r "../packages/Akka.Persistence.Cassandra/lib/net45/Akka.Persistence.Cassandra.dll"
#r "../packages/Akkling.Persistence/lib/net45/Akkling.Persistence.dll"

open System
open Akkling
open Akkling.Persistence
open Akka.Persistence.Cassandra

let configWith() =
    let config = Configuration.parse("""
akka {
    persistence {
        journal.plugin = "cassandra-journal"
        sessions.plugin = "cassandra-sessions"
        snapshot-store.plugin = "cassandra-snapshot-store"

        cassandra-sessions {
            # The "default" Cassandra session, used by both the journal and snapshot store if not changed in 
            # the cassandra-journal and cassandra-snapshot-store configuration sections below
            default {
                # Comma-seperated list of contact points in the cluster in the format of either [host] or [host:port]
                contact-points = [ "192.168.56.101" ]

                # Default port for contact points in the cluster, used if a contact point is not in [host:port] format
                port = 9042
            }
        }

        cassandra-journal {
            # Type name of the cassandra journal plugin
            class = "Akka.Persistence.Cassandra.Journal.CassandraJournal, Akka.Persistence.Cassandra"

            # The name (key) of the session to use when resolving an ISession instance. When using default session management,
            # this points at configuration under the "cassandra-sessions" section where the session's configuration is found.
            session-key = "default"

            # Whether or not to quote table and keyspace names when executing statements against Cassandra
            use-quoted-identifiers = false

            # The keyspace to be created/used by the journal
            keyspace = "akkanet"
            
            # A string to be appended to the CREATE KEYSPACE statement after the WITH clause when the keyspace is 
            # automatically created. Use this to define options like replication strategy.
            keyspace-creation-options = "REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 }"

            # When true the journal will automatically try to create the keyspace if it doesn't already exist on start
            keyspace-autocreate = true

            # Name of the table to be created/used by the journal
            table = "messages"

            # A string to be appended to the CREATE TABLE statement after the WITH clause. Use this to define things
            # like gc_grace_seconds or one of the many other table options.
            table-creation-properties = ""

            # The approximate number of rows per partition to use. Cannot be changed after table creation.
            partition-size = 5000000

            # The maximum number of messages to retrieve in one request when replaying messages
            max-result-size = 50001
  
            # Consistency level for reads
            read-consistency = "Quorum"

            # Consistency level for writes
            write-consistency = "Quorum"
        }

        cassandra-snapshot-store {
            # Type name of the cassandra snapshot store plugin
            class = "Akka.Persistence.Cassandra.Snapshot.CassandraSnapshotStore, Akka.Persistence.Cassandra"

            # The name (key) of the session to use when resolving an ISession instance. When using default session management,
            # this points at configuration under the "cassandra-sessions" section where the session's configuration is found.
            session-key = "default"

            # Whether or not to quote table and keyspace names when executing statements against Cassandra
            use-quoted-identifiers = false

            # The keyspace to be created/used by the snapshot store
            keyspace = "akkanet"

            # A string to be appended to the CREATE KEYSPACE statement after the WITH clause when the keyspace is 
            # automatically created. Use this to define options like replication strategy.
            keyspace-creation-options = "REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 }"

            # When true the journal will automatically try to create the keyspace if it doesn't already exist on start
            keyspace-autocreate = true

            # Name of the table to be created/used by the snapshot store
            table = "snapshots"

            # A string to be appended to the CREATE TABLE statement after the WITH clause. Use this to define things
            # like gc_grace_seconds or one of the many other table options.
            table-creation-properties = ""

            # The maximum number of snapshot metadata instances to retrieve in a single request when trying to find a
            # snapshot that matches the criteria
            max-metadata-result-size = 10
  
            # Consistency level for reads
            read-consistency = "One"

            # Consistency level for writes
            write-consistency = "One"
        }
    }
}
    """)
    config.WithFallback(CassandraPersistence.DefaultConfig())

let system = System.create "example" <| configWith()

type CounterChanged =
    { Delta : int }

type CounterCommand =
    | Inc
    | Dec
    | GetState

type CounterMessage =
    | Command of CounterCommand
    | Event of CounterChanged

let counter =
    spawn system "counter-1" <| propsPersist(fun mailbox ->
        let rec loop state =
            actor {
                let! msg = mailbox.Receive()
                match msg with
                | Event(changed) -> return! loop (state + changed.Delta)
                | Command(cmd) ->
                    match cmd with
                    | GetState ->
                        mailbox.Sender() <! state
                        return! loop state
                    | Inc -> return Persist (Event { Delta = 1})
                    | Dec -> return Persist (Event { Delta = -1})
            }
        loop 0)

counter <! Command Inc
counter <! Command Inc
counter <! Command Dec
async {
    let! reply = counter <? Command GetState
    printfn "Current state of %A: %i" counter reply
} |> Async.RunSynchronously
```

Anybody understand what I have done wrong? Any help is appreciated :)

**Comment by Horusiath** [comment]
I think, that Cassandra plugin has not been updated for a while. I'll set an issue on the corresponding repo.

**Comment by Horusiath** [comment]
I'll close this one. Please track the issue on cassandra repo. I'll try to work on the update this week.

**Comment by HIPERCUBE** [comment]
@Horusiath @MClode I have a same issue.
Is there any progress?
